version: "3.1"
services:
  jenkins:
    build:
      context: .
    image: jenkins
    container_name: jenkins
    ports:
     - "8080:8080"
   # depends_on:
   #  - nexus
   # links:
   #   - nexus
    volumes:
     - "./jobs:/var/jenkins_home/jobs/"
     - "./m2deps:/var/jenkins_home/.m2/repository/"
     - "./downloads:/var/jenkins_home/downloads"
    environment:
     - NEXUS_RELEASES_URL=http://nexus:8081/repository/maven-releases/
     - NEXUS_SNAPSHOTS_URL=http://nexus:8081/repository/maven-snapshots/
#    secrets:
#     - artifactoryPassword
#  nexus:
#    image: sonatype/nexus3
#    container_name: nexus
#    ports:
#     - "8081:8081"
#    volumes:
#     - "./nexus-data:/nexus-data"
#secrets:
# artifactoryPassword:
#  file: ./secrets/artifactoryPassword
